[package]
name = "maybe_path"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "vs_path"
harness = false

[[bench]]
name = "vs_cow"
harness = false